### ISSUE TITLE
forcePull in TaskDef not used when creating tasks

### ISSUE THREAD

**Issue by alvarolopez** [adobe-apiplatform/mesos-actor#51]
Hi.

I am not a Scala programmer, so I might be wrong. It seems that the forcePull paramter, although defined in the TaskDef is never passed to Mesos.

The `forcePull` parameter is defined here: https://github.com/adobe-apiplatform/mesos-actor/blob/master/src/main/scala/com/adobe/api/platform/runtime/mesos/MesosClient.scala#L108 but it is not being used here: https://github.com/adobe-apiplatform/mesos-actor/blob/master/src/main/scala/com/adobe/api/platform/runtime/mesos/TaskBuilder.scala#L63

**Comment by tysonnorris** [comment]
I think you are right; Will get it fixed.
